name: CI - Build, Test & SonarCloud

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-sonar:
    runs-on: ubuntu-latest
    continue-on-error: true  

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Quan trọng để Sonar phân tích lịch sử git

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
              args: >
                -Dsonar.projectKey=thangnvhe
                -Dsonar.organization=thangnvhe
                -Dsonar.host.url=https://sonarcloud.io
                -Dsonar.qualitygate.wait=false

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"
